name = "Bicep Parameters"
grammar = "bicep"
path_suffixes = ["bicepparam"]
line_comments = ["// "]
block_comments = ["/*", "*/"]
autoclose_before = ":.,=}])' \n\t"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "'", end = "'", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "'''", end = "'''", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
    { start = "/*", end = "*/", close = true, newline = false, not_in = [
        "string",
        "comment",
    ] },
]
tab_size = 2
