repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^grammars/
      - id: end-of-file-fixer
        exclude: ^grammars/
      - id: check-toml
        exclude: ^grammars/
      - id: check-json
      - id: check-yaml

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --target wasm32-wasip2 -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
