id = "bicep"
name = "Bicep"
description = """
Bicep language support. Bicep is a Domain Specific Language (DSL) created by Microsoft for deploying Azure resources declaratively. This extension provides intellisense for the core language and extends to support type definitions for all resource types in Azure.
"""
version = "0.0.0-dev"
schema_version = 1
repository = "https://github.com/oWretch/zed-extension-bicep"
authors = [ "Jerome Brown <Jerome@SoliDeoGloria.tech>" ]

[grammars.bicep]
repository = "https://github.com/oWretch/tree-sitter-bicep"
commit = "8288b2b7a0313842d3b2997b36bf1cbd2b60abc0"

[language_servers.bicep-ls]
name = "Bicep Language Server"
languages = [ "Bicep" ]
